# Introduction

I hope that as you work throught his book you will gain several things:

- an understanding of the value of being a numerate person,
- a confidence in handling facts, figures and those pesky statistics,
- and an enjoyment in learning more about the world we live in.

## Why Core maths?

It is a good question! As the world has become more technological it has brought great benefits, think of a single day in your life. You woke up and enjoyed a hot cup of tea or coffee without having to first clear out the fireplace or blow on embers to get the fire going! Whereas your ancestors gathered wood or mined coal for their energy needs you just flick a switch and electricity is there for you (lucky you!). The vast networks that balance the power load, spin up power stations at peak load times, transform voltages and span the county are basically invisible to you. They are just **there** available and always on. But the changes that they have brought to our society have been immeasurable - the hours your ancestors spent lighting fires can now be spent relaxing, or working in other ways. It's not just the kettle, but the washing machine, the vacuum cleaner, the hot water tank, the lights and any number of labour saving devices have been freeing up time year on year. That time has been a precious gift, a gift that has led inexorably to progress in our societies.

With the advent of widespread computing we have reached a new level of progress. Suddenly we are surrounded by a world of information, what once would have taken us days to dig out of the library is now almost instantly accessible. Options to share your creative works abound with new online technologies. We can gain access to more official statistics than ever before. 

What does this mean for you? It means simply that you need to be **numerate**. Since the 1800's we have enjoyed the benefits of a literacy revolution through an educated and politically engaged populace, today we are beginning to see the need for a numeracy revolution. It isn't enough any more to merely pass your GCSE maths qualification, you need to be able to go beyond that and be able to apply those skills in the real world.

We have in the workplace unprecedented demand for students who can "do numbers", and this doesn't just mean financial literacy, althoughit does mean that. To be able to "do numbers" means that your boss can give you the sales records for the past three years from five different stores and ask you which one to close and which one to invest more in. This isn't the maths you are used to! It requires argument and interpretation, decision making and justification.
