# Modelling

## The modelling cycle

Key Skills:

- p1 Be able to identify simplifying assumptions that allow a situation to be modelled.
- p2 Be able to develop or choose a simple mathematical model for a real-world situation.
- p3 Be able to use a model to make predictions or get information about a situation.
- p4 Be able to compare the outcomes from a model with actual data, information, experience or common sense and comment on the appropriateness of the model.
- p5 Be able to appraise the assumptions underlying a model critically.
- p6 Understand that a simple model can give useful answers but may need to be improved.
- p7 Be able to communicate mathematical results clearly and effectively.

## Estimation

Key Skills:

- e1 Be able to make a rough estimate of a quantity from available information.
- e2 Be able to use estimates when checking calculations.
- e3 Be able to make and justify upper and lower bounds for a calculation.
- e4 Be able to interpret and present error bounds or tolerances on diagrams and in writing, understanding that different levels of tolerance are appropriate in different situations.

## Algebra

Key Skills:

- a1 Be able to represent a situation mathematically using a formula or equation.
- a2 Be able to substitute values into a formula given in symbols, words or as a flow chart.
- a3 Be able to solve equations and change the subject of a formula.

## Geometry and Measures

Key Skills:

- m1 Be able to recognise and use relationships between lengths, areas, weights and volumes of similar figures to model real-world situations.
- m2 Be able to work with time, length, area and volume to meet given regulations
- m3 Be able to work with commonly used units and know that quantities being compared should have the same units; this includes compound units.
- m4 Be able to interpret diagrams, maps and scale drawings and be able to use them in problem solving.
- m5 Be able to work with representations of 3-D objects in 2-D.
- m6 Understand the terms displacement, distance, velocity, speed and acceleration; perform associated calculations.

## Number

Key Skills:

- n1 Be able to use ratio and proportionality in realistic contexts
