# (PART) Statistical Problem Solving {-}

# Problem Analysis


## Strategies for Problem Solving

Key Skills:

- s1 Be able to formulate a problem in a way that lends itself to statistical approaches.
- s2 Consider different statistical approaches to a problem.

## Selecting a model

Key Skills:

- s3 Be able to select an appropriate standard distribution as a model.
- s4 Recognise where a standard statistical procedure may be used.
- s5 Be aware of any modelling assumptions involved in using a distribution or procedure that has been selected.

## Inputs

Key Skills:

- s6 Be able to identify what inputs a model requires.
- s7 Be able to design a procedure for collecting the necessary input data for a model.
- s8 Understand the sources of variability in data and their implications in the context of a model and its inputs.

## Inference

Key Skills:

- h1 Understand the process of hypothesis testing, including using the associated vocabulary.
- h2 Be aware that large data sets can be h2 representative of underlying populations and can be used to draw conclusions.

## Sampling

Key Skills:

- s9 Know and be able to use suitable sampling methods in appropriate contexts.

## Information Sources

Key Skills:

- e1 Be able to call on factual general knowledge.
- e2 Be able to make reasonable estimates of quantities met in everyday life without additional information.
- s10 Be able to find and use relevant information from a variety of sources.
- s11 Be able to evaluate critically information in public statements such as news reports and political comments.
- s12 Be able to understand accounts of statistical work done by others and comment on its quality.
