# Process and Presentation

## Raw Data

Key Skills:

- s13 Be able to select suitable techniques for processing raw data.
- s14 Be able to clean data including dealing with missing data and outliers

## Graphs, Charts and Summary Measures

Key Skills:

- s15 Be able to select suitable data displays and summary measures to show the main features of raw data.
- s16 Be able to use data displays to check whether distributions being used are realistic.

## Parameters and Inputs; Calculations

Key Skills:

- s17 Use standard statistical notation for samples.
- s18 Be able to use sample data to estimate the parameters of a distribution or the inputs for a procedure or model.
- s19 Be able to use the statistical functions of a calculator to find the mean and standard deviation.
- s20 Understand the use of a datum level as a base for measurement or calculation.
- s21 Know how the mean and standard deviation are affected by linear transformations.
- s22 Be able to substitute input values into a model or procedure.

## The Normal Distribution in Depth

Key Skills:

- u1 Be able to use the Normal distribution as a model and recognise when it is likely to be appropriate to do so.
- u2 Be able to standardise a value from a Normal distribution with a given mean and standard deviation.
- u3 Use the Normal distribution to estimate population proportions in the context of a problem.

## The Chi Squared Test

Key Skills:

- h3 Be able to apply the χ² hypothesis test to data in a contingency table.
- h4 Be able to interpret the χ² results of a test.

## Bivariate Data

Key Skills:

- b1 Know the vocabulary associated with bivariate data.

### Relationships between variables

Real life data often comes in pairs. Scratch that, it often comes in lists! When we gather data about a group of people, say, we will gain a whole list of information about each individual. Bivariate data analysis (literally two variables) is the first step on a long road of statistical techniques that enables you to seek out and find the relationships between that long list of variables.

Lucky for you we will only be looking at data that comes in pairs!

For example even though in the country data below you have access to many different variables at this level you will only analyse a pair of variables suc as the relationship between GDP per capita and population or life expectancy and birth rate.

```{r country-data, echo = FALSE}
install.packages("install.load")
library(install.load)
install_load(xlsx)
countryData = read.xlsx("./data/09-06-country-data.xlsx", sheetName="merged with region")

knitr::kable(
  head(mtcars[, 1:10], 15), booktabs = TRUE,
  caption = 'Country Data.'
)

```

## Spearman's Rank Correlation

Key Skills:

- b2 Know how to calculate Spearman's rank correlation coefficient and carry out hypothesis tests using it.

## Product Moment Correlation

Key Skills:

- b3 Be able to use suitable technology to find Pearson’s product moment correlation coefficient and to interpret the correlation coefficient.
